-- Dedicated end-to-end test from Master through an AP and VSAT to an internet/server target.
CREATE TABLE IF NOT EXISTS `satellite_vsat_tests` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `test_date` DATE NOT NULL,
    `location_name` VARCHAR(100) NOT NULL,
    `test_operator` VARCHAR(100) NULL,
    `weather_condition` ENUM('cerah', 'berawan', 'hujan_ringan', 'hujan_lebat') NULL,
    `node_id` VARCHAR(50) NOT NULL DEFAULT 'MASTER-VSAT',
    `connection_mode` ENUM('WiFi AP + VSAT', 'Ethernet + VSAT') NOT NULL DEFAULT 'WiFi AP + VSAT',
    `access_point_ssid` VARCHAR(100) NOT NULL,
    `ip_assignment` ENUM('DHCP', 'Static') NULL DEFAULT 'DHCP',
    `master_ip` VARCHAR(45) NOT NULL,
    `gateway_ip` VARCHAR(45) NOT NULL,
    `wan_ip` VARCHAR(45) NULL,
    `vsat_provider` VARCHAR(100) NULL,
    `gateway_ping_status` ENUM('success', 'fail') NOT NULL,
    `server_target` VARCHAR(150) NOT NULL,
    `internet_ping_status` ENUM('success', 'fail') NOT NULL,
    `packet_sent` INT NOT NULL DEFAULT 10,
    `packet_received` INT NOT NULL DEFAULT 10,
    `latency_ms` DECIMAL(10,2) NULL,
    `jitter_ms` DECIMAL(10,2) NULL,
    `packet_loss_percent` DECIMAL(5,2) NULL,
    `download_kbps` DECIMAL(12,2) NULL,
    `upload_kbps` DECIMAL(12,2) NULL,
    `wifi_rssi_dbm` DECIMAL(6,2) NULL,
    `wifi_snr_db` DECIMAL(6,2) NULL,
    `vsat_lock_status` ENUM('locked', 'unlocked', 'not_checked') NOT NULL,
    `rx_signal_type` ENUM('SNR', 'C/N', 'Eb/N0') NULL,
    `rx_signal_db` DECIMAL(8,2) NULL,
    `tx_power_dbm` DECIMAL(8,2) NULL,
    `modem_uptime_minutes` BIGINT NULL,
    `rain_fade_status` ENUM('none', 'mild', 'moderate', 'severe', 'not_checked') NULL DEFAULT 'not_checked',
    `data_usage_mb` DECIMAL(12,2) NULL,
    `server_protocol` ENUM('MQTT', 'HTTP API', 'HTTPS API', 'other', 'not_tested') NULL DEFAULT 'not_tested',
    `server_delivery_status` ENUM('success', 'fail', 'not_tested') NULL DEFAULT 'not_tested',
    `reconnect_count` INT NULL DEFAULT 0,
    `last_successful_send` DATETIME NULL,
    `evidence_link` VARCHAR(255) NULL,
    `overall_status` ENUM('passed', 'partial', 'failed') NOT NULL DEFAULT 'partial',
    `notes` TEXT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_satellite_vsat_test_date` (`test_date`),
    INDEX `idx_satellite_vsat_status` (`overall_status`)
);
