<?php
$pageConfig = [
    'title' => 'Interference Test',
    'icon' => 'fas fa-wifi',
    'description' => 'Input bukti spektrum RF 860–930 MHz dan dampaknya pada koneksi master–slave.',
    'table' => 'interference_tests',
    'order' => 'test_date DESC, created_at DESC',
    'chart_label_fields' => ['scan_status', 'distance_meter'],
    'chart_label_caption' => 'Label grafik: status pemindaian SDR - jarak',
    'chart_metrics' => [
        ['field' => 'throughput_kbps', 'label' => 'Throughput', 'unit' => 'kbps', 'type' => 'line'],
        ['field' => 'latency_ms', 'label' => 'Latency', 'unit' => 'ms', 'type' => 'bar'],
        ['field' => 'packet_loss_percent', 'label' => 'Packet Loss', 'unit' => '%', 'type' => 'bar'],
        ['field' => 'snr_db', 'label' => 'SNR', 'unit' => 'dB', 'type' => 'line'],
        ['field' => 'noise_floor_dbm', 'label' => 'Noise Floor', 'unit' => 'dBm', 'type' => 'line'],
    ],
    'chart_status_field' => 'scan_status',
    'chart_notes' => [
        'Status detected hanya dipilih bila puncak sinyal non-HaLow terlihat pada hasil SDR.',
        'Noise floor, frekuensi dan daya pengganggu menjadi bukti RF; metrik koneksi menunjukkan dampaknya.',
    ],
    'fields' => [
        ['name' => 'test_date', 'label' => 'Test Date', 'type' => 'date', 'required' => true],
        ['name' => 'location_name', 'label' => 'Location Name', 'required' => true],
        ['name' => 'environment_type', 'label' => 'Environment Type', 'type' => 'select', 'options' => ['lapangan', 'hangar', 'pantai', 'gunung', 'indoor', 'outdoor']],
        ['name' => 'scan_status', 'label' => 'SDR Scan Status', 'type' => 'select', 'required' => true, 'default' => 'not_scanned', 'options' => ['not_scanned', 'clear', 'detected', 'inconclusive']],
        ['name' => 'scan_start_mhz', 'label' => 'Scan Start (MHz)', 'type' => 'number', 'step' => '0.01', 'default' => 860],
        ['name' => 'scan_end_mhz', 'label' => 'Scan End (MHz)', 'type' => 'number', 'step' => '0.01', 'default' => 930],
        ['name' => 'noise_floor_dbm', 'label' => 'Noise Floor (dBm)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'strongest_interferer_frequency_mhz', 'label' => 'Strongest Interferer Frequency (MHz)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'strongest_interferer_power_dbm', 'label' => 'Strongest Interferer Power (dBm)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'channel_occupancy_percent', 'label' => 'Channel Occupancy (%)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'sdr_device', 'label' => 'SDR Device'],
        ['name' => 'interference_evidence', 'label' => 'Spectrum Evidence / File Link', 'type' => 'textarea'],
        ['name' => 'interference_level', 'label' => 'Impact Level', 'type' => 'select', 'options' => ['normal', 'low', 'medium', 'high']],
        ['name' => 'interference_source', 'label' => 'Suspected RF Source / Signal'],
        ['name' => 'distance_meter', 'label' => 'Distance (m)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'rssi_dbm', 'label' => 'RSSI (dBm)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'snr_db', 'label' => 'SNR (dB)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'throughput_kbps', 'label' => 'Throughput (kbps)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'latency_ms', 'label' => 'Latency (ms)', 'type' => 'number', 'step' => '0.01'],
        ['name' => 'packet_sent', 'label' => 'Packet Sent', 'type' => 'number', 'integer' => true, 'default' => 1000],
        ['name' => 'packet_received', 'label' => 'Packet Received', 'type' => 'number', 'integer' => true, 'default' => 1000],
        ['name' => 'notes', 'label' => 'Notes', 'type' => 'textarea'],
    ],
    'calculate' => function ($data) {
        return [
            'packet_loss_percent' => calculatePacketLoss($data['packet_sent'] ?? null, $data['packet_received'] ?? null),
            'throughput_degradation_percent' => null,
            'latency_increase_percent' => null,
            'snr_degradation_db' => null,
        ];
    },
    'formulas' => [
        'Packet Loss % = (Packet Lost / Packet Sent) x 100',
        'Status detected memerlukan bukti puncak sinyal SDR; status clear berarti tidak ada puncak pengganggu terukur.',
        'Throughput degradation, latency increase, dan SNR degradation disimpan kosong bila tidak ada baseline.',
    ],
    'columns' => [
        ['label' => 'Date', 'field' => 'test_date', 'format' => 'date'],
        ['label' => 'Location', 'field' => 'location_name'],
        ['label' => 'SDR Status', 'field' => 'scan_status', 'format' => 'status'],
        ['label' => 'Noise Floor', 'field' => 'noise_floor_dbm', 'decimals' => 2, 'suffix' => ' dBm'],
        ['label' => 'Strongest Frequency', 'field' => 'strongest_interferer_frequency_mhz', 'decimals' => 2, 'suffix' => ' MHz'],
        ['label' => 'Strongest Power', 'field' => 'strongest_interferer_power_dbm', 'decimals' => 2, 'suffix' => ' dBm'],
        ['label' => 'Throughput', 'field' => 'throughput_kbps', 'decimals' => 2, 'suffix' => ' kbps'],
        ['label' => 'Latency', 'field' => 'latency_ms', 'decimals' => 2, 'suffix' => ' ms'],
        ['label' => 'Packet Loss', 'field' => 'packet_loss_percent', 'decimals' => 2, 'suffix' => '%'],
    ],
];

include __DIR__ . '/_test_page.php';
